name: docs

on:
  - push

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: "3.6"

      - name: Install dependencies
        run: pip install tox

      - name: Build with tox
        run: tox -e docs
