name: publish

on:
  push:
    tags:
      - "**"

jobs:
  publish:
    name: Publish on PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/minelog
    permissions:
      id-token: write
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up project and environment
        uses: ./.github/actions/setup-project

      - name: Check the tag
        run: uv run poe check-tag

      - name: Runn all tests
        run: uv run poe check

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
